[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["spikes"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/zeeshanhaque21/cowfs"
publish = false

[workspace.dependencies]
blake3 = "1"
thiserror = "2"
proptest = "1"
tempfile = "3"

[workspace.lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[profile.release]
debug = "line-tables-only"
